//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Site.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Aidat
    {
        public int AidatID { get; set; }
        public int DaireID { get; set; }
        public string AidatAyi { get; set; }
        public double AidatTutari { get; set; }
        public string OdemeDurumu { get; set; }
    
        public virtual Daire Daire { get; set; }
    }
}
