//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Site.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Fatura
    {
        public int FaturaID { get; set; }
        public int DaireID { get; set; }
        public string FaturaTipi { get; set; }
        public string Ay { get; set; }
        public double Tutar { get; set; }
    
        public virtual Daire Daire { get; set; }
    }
}
