//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Site.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class site_dbEntities4 : DbContext
    {
        public site_dbEntities4()
            : base("name=site_dbEntities4")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Aidat> Aidat { get; set; }
        public virtual DbSet<Blok> Blok { get; set; }
        public virtual DbSet<Daire> Daire { get; set; }
        public virtual DbSet<Doluluk> Doluluk { get; set; }
        public virtual DbSet<Fatura> Fatura { get; set; }
        public virtual DbSet<Mülkiyet> Mülkiyet { get; set; }
        public virtual DbSet<Otopark> Otopark { get; set; }
        public virtual DbSet<Sakin> Sakin { get; set; }
        public virtual DbSet<users> users { get; set; }
    }
}
