//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Site.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Otopark
    {
        public int OtoparkID { get; set; }
        public int DaireID { get; set; }
        public string Plaka { get; set; }
        public Nullable<double> UcretliParkYeriTutari { get; set; }
        public Nullable<int> AracSayisi { get; set; }
    
        public virtual Daire Daire { get; set; }
    }
}
